#
#
#
#How Mastery Works -> 50 = 0-49, 349 = 300-349, 599 = 550-599
#

Gathering:
  Lumbering: #Lumbering LifeSkill
    Mastery:
      50:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:       #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      100:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      150:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      200:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      250:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      300:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      350:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      400:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      450:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      500:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      550:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      600:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      650:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      700:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      750:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      800:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      850:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      900:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      950:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1000:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1050:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1100:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1150:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1200:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1250:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1300:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1350:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1400:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1450:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1500:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1550:
        Common: #Tier 1 Mats - Logs
          Min: 1
          Max: 1
          Chance: 1000
        Uncommon: #Tier 2 Mats - Processed Logs/Miscellaneous
          Min: 1
          Max: 1
          Chance: 100
        Rare:         #Mats - Basic Enhancement Materials, Basic Crafting Mats
          Min: 1
          Max: 1
          Chance: 20
        Legendary:    #Tier 3 Mats - Advanced Enhancement Materials, Advanced Crafting Mats
          Min: 1
          Max: 1
          Chance: 5
      1600:
        Common:
          Min: 2
          Max: 4
          Chance: 1000
        Rare:
          Min: 1
          Max: 1
          Chance: 51
        Legendary:
          Min: 1
          Max: 1
          Chance: 5
      1650:
        Common:
          Min: 2
          Max: 4
          Chance: 1000
        Rare:
          Min: 1
          Max: 1
          Chance: 51
        Legendary:
          Min: 1
          Max: 1
          Chance: 5
      1700:
        Common:
          Min: 2
          Max: 4
          Chance: 1000
        Rare:
          Min: 1
          Max: 1
          Chance: 51
        Legendary:
          Min: 1
          Max: 1
          Chance: 5
      1750:
        Common:
          Min: 2
          Max: 4
          Chance: 1000
        Rare:
          Min: 1
          Max: 1
          Chance: 51
        Legendary:
          Min: 1
          Max: 1
          Chance: 5
      1800:
        Common:
          Min: 2
          Max: 4
          Chance: 1000
        Rare:
          Min: 1
          Max: 1
          Chance: 51
        Legendary:
          Min: 1
          Max: 1
          Chance: 5
      1850:
        Common:
          Min: 2
          Max: 4
          Chance: 1000
        Rare:
          Min: 1
          Max: 1
          Chance: 51
        Legendary:
          Min: 1
          Max: 1
          Chance: 5
      1900:
        Common:
          Min: 2
          Max: 4
          Chance: 1000
        Rare:
          Min: 1
          Max: 1
          Chance: 51
        Legendary:
          Min: 1
          Max: 1
          Chance: 5
      1950:
        Common:
          Min: 2
          Max: 4
          Chance: 1000
        Rare:
          Min: 1
          Max: 1
          Chance: 51
        Legendary:
          Min: 1
          Max: 1
          Chance: 5
      2000:
        Common:
          Min: 2
          Max: 4
          Chance: 1000
        Rare:
          Min: 1
          Max: 1
          Chance: 51
        Legendary:
          Min: 1
          Max: 1
          Chance: 5
    LogXP:
      Multiplier: 1.0
      ACACIA: 5.0
      BIRCH: 5.0
      DARK_OAK: 5.0
      SPRUCE: 5.0
      OAK: 5.0
      JUNGLE: 5.0

  Butchering: #Butchering LifeSkill
    MeatXP:
      PORK: 5.0
      BEEF: 5.0
      MUTTON: 5.0
      CHICKEN: 5.0
      RABBIT: 5.0

  Mining: #Mining LifeSkill
    BlockXP:
      STONE: 1.0
      COAL: 3.0
      IRON: 5.0
      GOLD: 7.0
      REDSTONE: 7.0
      LAPIS: 7.0
      EMERALD: 15.0
      DIAMOND: 12.0
      QUARTZ: 5.0
      DEBRIS: 20.0
      NETHERACK: 1.0

Cooking: #Cooking LifeSkill
Alchemy: #Alchemy LifeSkill
Riding: #Riding LifeSkill
Fishing: #Fishing LifeSkill