name: LifeSkills
version: ${project.version}
main: me.tanko_.lifeskills.LifeSkills
api-version: 1.16
commands:
  tgive:
    description: give player a customitem
    usage: /<command> <target player> <item>
  guimenu:
    description: opens gui menu
    usage: /<command>
